### ISSUE TITLE
Missing hashCode Implementation in Principal Class Causes Duplicate Entries in Sets

### ISSUE THREAD

**Issue by chinaryov** [ic4j/ic4j-candid#4]
Hello ic4j Team,

I am writing to report an issue I've encountered while using the ic4j library, which has been otherwise very beneficial for my projects. The issue pertains to the `Principal` class not having an implemented `hashCode` method.

**Issue Description:**
When creating two instances of the `Principal` class with the same value and adding them to a `Set`, the `Set` mistakenly contains two instances instead of one. This is contrary to the expected behavior where a `Set` should automatically handle and prevent duplicate entries. 

**Impact:**
This behavior affects the data integrity when using `Sets` to store unique `Principal` instances, leading to potential bugs and unexpected behaviors in applications relying on the ic4j library.

**Expected Behavior:**
Ideally, the `Principal` class should override the `hashCode` method (alongside `equals`) to ensure that two `Principal` instances with the same value are treated as equal by collection classes like `Set`.

**Suggested Solution:**
Implementing the `hashCode` method in the `Principal` class, ideally in a manner consistent with the `equals` method, would resolve this issue.

**Example for Reproduction:**

Code snippet to demonstrate the issue
```
Set<Principal> principals = new HashSet<>();
Principal principal1 = Principal.fromString("tdmfb-hvxfs-w4yoo-hmigb-vy52k-7bf2v-mjg6i-luxix-xoxk7-55h6z-nqe");
Principal principal2 = Principal.fromString("tdmfb-hvxfs-w4yoo-hmigb-vy52k-7bf2v-mjg6i-luxix-xoxk7-55h6z-nqe");
principals.add(principal1);
principals.add(principal2);

System.out.println("Set size should be 1, but is: " + principals.size());
```

This issue is crucial for the proper functioning of sets and maps in Java, where unique identification of objects is often required. I hope this can be addressed in a future update. Thank you for your attention to this matter and for your continued work on the ic4j library.

Best regards,
Alexander

**Comment by rdobrik** [comment]
Hi Alexander, thank you for reporting this issue. Let me fix it and publish the patch ASAP.

**Comment by rdobrik** [comment]
Alexander, I added those to functions to Principal class. You can check code in GitHub. Also released patch for ic4j-candid package to Maven Central. Version is 0.6.19.7. I added some unit tests for both functions. Let me know if it works for you or if you see any issues we should fix.

**Comment by chinaryov** [comment]
Dear Roman,

I wanted to express my gratitude for your swift response and fix regarding the hashCode issue in the Principal class of the ic4j library. I've tested the update, and I'm pleased to report that it works perfectly. Your prompt and effective action is greatly appreciated and enhances the user experience significantly. Thank you for your dedication and support to the ic4j community.

Best regards,
Alexander

**Comment by rdobrik** [comment]
Alexander, happy to hear that the fix works well! This is important feature. I will also check other classes where hashCode and equals functions will make sense. Please, keep reporting these issues!

Roman
